package string.easy;

import java.util.HashMap;
import java.util.Map;

/*
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
 */
public class FindTheDifference {

    // Brute force approach
    public char findTheDifference(String s, String t) {
        Map<Character, Integer> map = new HashMap<>();

        // Push all the chars of string s in the map
        for (Character ch : s.toCharArray()) {
            map.put(ch, map.getOrDefault(ch, 0) + 1);
        }

        // Iterate over the string s
        for (int i = 0; i < t.length(); i++) {
            char ch = t.charAt(i);

            // check if map contains the char
            if (map.containsKey(ch)) {
                int freq = map.get(ch); // get frequency of the char
                freq--; // reduce it
                if (freq == 0) {  // if freq is zero remove it from the map
                    map.remove(ch);
                } else {        // else update the freq
                    map.put(ch, freq);
                }
            }
            // if does not contain the char ( that's the answer)
            else {
                return ch;
            }
        }

        // iterate over the map
        for (Map.Entry<Character, Integer> entry : map.entrySet()) {
            // if the value id still remain that means that is (char) is the answer
            if (entry.getValue() == 1) {
                return entry.getKey();
            }
        }

        // return something (since everything is inside the loop)
        return ' ';
    }

    // Optimal solution
    public char findTheDifference2(String s, String t) {
        if(s.isEmpty()){
            return t.charAt(0);
        }

        int sumS = 0;
        int sumT = 0;

        for(char ch : s.toCharArray()){
            sumS += ch;
        }

        for(char ch : t.toCharArray()){
            sumT += ch;
        }

        // difference is the extra char
        return (char)(sumT - sumS);
    }
}
